### ISSUE TITLE
[Mac OS X] Creates plenty of whitespace in the output file

### ISSUE THREAD

**Issue by mjurczyk** [djanowski/hasp#2]
After using the command on Mac OS X 10.10.1:

```
./bin/hasp examples/foo.hcss > test.css
```

test.css contains a hell lot of whitespace:

``` css
























body {
  font-size: 2em;
  color: #f00;
}

section {
  background-color: #ff0;




}





@media only screen and (min-device-width: 768px) {
  section {
    font-family: monospace;
    width: 70%;
  }
}

@media only screen and (min-device-width: 900px) {
  section {
    font-family: sans-serif;
    width: 50%;
  }
}




```
